# This is a basic workflow to help you get started with Actions

name: Create New Session Host

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/new-session-host.yml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/new-session-host.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      SIG: sigseaib
      RESOURCE_GROUP: rg-images
      IMAGE_DEFINITION: se-wvd
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_AIRS }}
          enable-AzPSSession: true 
      
      - name: Get Az Gallery Image Version & Deploy Host
        shell: pwsh
        env:
          D_USER: ${{ secrets.DOMAINUSERNAME }}
          D_PASSWORD: ${{ secrets.DOMAINPASSWORD }}
          VM_USER: ${{ secrets.LOCALUSERNAME }}
          VM_PASSWORD: ${{ secrets.LOCALPASSWORD }}
          STORAGE: ${{ secrets.BOOT_STORAGE_URI }}
          REG_TOKEN: ${{ secrets.REGISTRATIONINFOTOKEN }}
        run: |
          $SIG = $env:SIG 
          $rg = $env:RESOURCE_GROUP.toLower()
          $storage = $env:STORAGE
          $image_def = $env:IMAGE_DEFINITION
          $rand = (65..90) + (97..122) | Get-Random -Count 5 | % { [char]$_ } | join-string 
          $month_day = (get-date -F MMdd)
          $deployment_name = "new-session-host-$month_day-$rand"
          $vm_name = "se-sh-$month_day-$rand"
          $template_file = "session-host-creation/session-host.bicep"
          $params_file = "session-host-creation/session-host.params.json"
          $session_host_rg = "rg-se-wvd"

          echo $month_day
          echo $deployment_name
          echo $storage

          $image_ver = az sig image-version list -g $rg -r $SIG -i $image_def --query "[].[name]" -o tsv | sort -r | head -n 1

          az deployment group create --resource-group $session_host_rg --template-file $template_file --parameters $params_file --parameters registrationInfoToken=$env:REG_TOKEN galleryImageVersionName=$image_ver domainUsername=$env:D_USER domainPassword=$env:D_PASSWORD dnsLabelPrefix=$vm_name vmAdminUsername=$env:VM_USER bootStorageURI=$storage vmAdminPassword=$env:VM_PASSWORD --name $deployment_name


           