# This is a basic workflow to help you get started with Actions

name: Create New Session Host

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      SIG: sigseaib
      RESOURCE_GROUP: rg-images
      IMAGE_DEFINITION: se-wvd
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS_AIRS }}
         
      # Runs a set of commands using the runners shell
      - name: Get Az Gallery Image Version
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Get-AzGalleryImageVersion -GalleryName $env:SIG -ResourceGroupName $env:RESOURCE_GROUP -GalleryImageDefinitionName $env:IMAGE_DEFINITION | select @{Name="Date";E={$_.PublishingProfile.PublishedDate}},Name | Sort-Object -Descending Date | select -First 1 -ExpandProperty Name
          azPSVersion: "latest"