# This is a basic workflow to help you get started with Actions

name: Create New Session Host

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ build-session-host ]
  pull_request:
    branches: [ build-session-host ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      SIG: sigseaib
      RESOURCE_GROUP: rg-images
      IMAGE_DEFINITION: se-wvd
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_AIRS }}
          enable-AzPSSession: true 

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 'latest'
          inlineScript: |
            az bicep install

            echo $PATH
            export PATH=/home/runner/.azure/bin/:$PATH
            echo $PATH  

      # Runs a set of commands using the runners shell
      - name: Get Az Gallery Image Version
        uses: Azure/powershell@v1
        env:
          D_USER: ${{ secrets.DOMAINUSERNAME }}
          D_PASSWORD: ${{ secrets.DOMAINPASSWORD }}
          VM_USER: ${{ secrets.LOCALUSERNAME }}
          VM_PASSWORD: ${{ secrets.LOCALPASSWORD }}
          REG_TOKEN: ${{ secrets.REGISTRATIONINFOTOKEN }}
        with:
          inlineScript: |
            $SIG = $env:SIG 
            $rg = $env:RESOURCE_GROUP
            $image_def = $env:IMAGE_DEFINITION
            $month_day = (get-date -F MMdd)
            $deployment_name = "new-session-host-$month_day"
            $vm_name = "se-sh-$month_day"
            $template_file = "session-host-creation/session-host.bicep"
            $params_file = "session-host-creation/session-host.params.json"
            $session_host_rg = "rg-se-wvd"

            get-azcontext
            $image_ver = Get-AzGalleryImageVersion -GalleryName $SIG -ResourceGroupName $rg -GalleryImageDefinitionName $image_def | select @{Name="Date";E={$_.PublishingProfile.PublishedDate}},Name | Sort-Object -Descending Date | select -First 1 -ExpandProperty Name
            New-AzResourceGroupDeployment -name $deployment_name -ResourceGroupName $session_host_rg -TemplateFile $template_file -TemplateParameterFile $params_file `
              -domainUsername $env:D_USER -domainPassword $env:D_PASSWORD -vmAdminUsername $env:VM_USER -vmAdminPassword $env:VM_PASSWORD -dnsLabelPrefix $vm_name `
              -registrationInfoToken $env:REG_TOKEN -galleryImageVersionName $image_ver
          azPSVersion: "latest"
      


           